### ISSUE TITLE
Feature Request: MIPS Support

### ISSUE THREAD

**Issue by zachriggle** [bdcht/amoco#11]
One of the things that I'd really like to see out of Amoco is to support the basic 32-bit MIPS ISA.  As it's a RISC architecture and not entirely dissimilar to ARM/SPARC, it shouldn't be too difficult.

Eventually I'll have time to do this, but I don't think it'll be until after DEFCON in August.

**Comment by bdcht** [comment]
Architecture added with PSX system.
