### ISSUE TITLE
"pop esp" incorrect

### ISSUE THREAD

**Issue by zachriggle** [bdcht/amoco#18]
The instruction `pop esp` does not add 4 to `esp` after popping.  Currently, Amoco treats it as effectively: `mov esp [esp]; add esp 0x4`, which is incorrect.

Thanks to @lieanu for pointing it out!

**Comment by bdcht** [comment]
thanks!

**Comment by zachriggle** [comment]
Looks good!

```
 268435469: Gadget(0x1000000d, [u'pop esp', u'ret'], {'eip': M32(M32(M32(esp)), #0), 'esp': ['M32(esp)']}, 0x4),
```
