### ISSUE TITLE
cas: simplification of ptr(cst, disp)

### ISSUE THREAD

**Issue by LRGH** [bdcht/amoco#33]
``` python
>>> ad=env.mem(env.cst(12,32),disp=4)
>>> str(ad.simplify())
'M32(0xc+4)'
```

I would have expected `'M32(0x10)'`

Proposed patch:

``` python
--- a/amoco/cas/expressions.py
+++ b/amoco/cas/expressions.py
@@ -960,6 +960,9 @@ class ptr(exp):
         if isinstance(self.seg,exp):
             self.seg = self.seg.simplify()
         if not self.base._is_def: self.disp=0
+        if self.disp and self.base._is_cst:
+            self.base += self.disp
+            self.disp = 0
         return self

     # default segment handler does not care about seg value:
```

**Comment by bdcht** [comment]
This is done on purpose to keep track of the 'base' address. You can check test_ptr and test_mem in tests/test_cas_exp.py to get the idea.

**Comment by LRGH** [comment]
I agree that `str(ad)` should return `'M32(0xc+4)'`.
But shouldn't `simplify` simplify the expression?
Shouldn't there be a simple way to assert that `env.mem(env.cst(12,32),disp=4)` is equal to `env.mem(env.cst(16,32))`?
