### ISSUE TITLE
Error in PE loader

### ISSUE THREAD

**Issue by securitea** [bdcht/amoco#4]
The PE loader was stopping reading after 179 bytes in some samples I was analysing. Tracked it down to the following line in system\pe.py:567

f = open(filename,'r')

The open mode should be 'rb', otherwise the stream terminates at invalid string characters.

Sorry for not doing the whole "fork and merge" thing, I'm lazy :)

**Comment by bdcht** [comment]
right, I tought 'b' was useless but its not the case for Windows and anyway it doesn't hurt...
fixed now
thx
