### ISSUE TITLE
x64: why do some arguments have 'mm' size?

### ISSUE THREAD

**Issue by LRGH** [bdcht/amoco#67]
In the x86 version, they have size 64.

``` python
>>> from amoco.arch.x64 import cpu_x64
>>> i=cpu_x64.disassemble('f\x0f\x16\x15\x0c\x00\x00\x00')
>>> str(i)
'movhpd      xmm2, cs:[rip+0xc]'
>>> str(i.operands[1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "amoco/cas/expressions.py", line 917, in __str__
    return 'M%d%s%s'%(self.size,n,self.a)
TypeError: %d format: a number is required, not str
>>> i.operands[1].size
'mm'
```

Not being able to do `str` prevents to do most operations, because `simplify` calls `eqn2_helpers` which compares outputs of `str`.

**Comment by bdcht** [comment]
No expression should have size 'mm' AFAIK. I will have a look.

**Comment by LRGH** [comment]
OK. I uploaded a commit that works on all my tests.

**Comment by LRGH** [comment]
My patch is very different from yours: it removes the creation of 'mm' size.
I don't know which is the best way, but my approach was done by looking at the diff between the x86 and x64 versions of `spec_sse.py`.

**Comment by bdcht** [comment]
well in x86, when opdsz is 64 there is no ambiguity since only mm regs are
64 bits long. In x64 we have to  distinguish regular 64bits regs from mm
regs... hence the added 'mm' key in env.getreg.

**Comment by LRGH** [comment]
"In x64 we have to distinguish regular 64bits regs from mm regs... hence the added 'mm' key in env.getreg."
OK. My patch prevents this, which is a problem.
I see it when parsing `0f 2d c0` for example.
