### ISSUE TITLE
pypy incompatible?

### ISSUE THREAD

**Issue by sqall01** [bdcht/amoco#71]
Hi,

I tried to use amoco with pypy to speed it up. It seems to work fine until I found the following. I have this code snippet:

``` python

    block_it = amoco_obj.iterblocks(0x80187214)

    for block in block_it:
        print "#"*80
        print block
        print "-----"
        print block.map
        print "\n"
```

When the line "print block.map" is reached with the python 2.7 interpreter, the output looks like this:

```
a10 <- { | [0:32]->(a10-0x8) | }
```

But when I execute it with pypy (pypy2-v5.4.1-linux64), it looks like this:

```
a10 <- [<amoco.cas.expressions.comp object at 0x0000000017dbee90>]
```

What I can tell so far is that the mapper class in the _ _ str _ _(self) function in this line:

```
return '\n'.join(["%s <- %s"%x for x in self])
```

has a list object for the right part of the string when using pypy, and an object from the cas.expressions file when using python.

This seems to come from the _ _ iter _ _(self) function which makes an iteritems() on the __map attribute of the mapper class. It seems that the "generation" class in cas.tracker.py has something to do with this. Do you have an idea what it could be?

Cheers,

sqall

**Comment by sqall01** [comment]
Perhaps this difference has something to do with it?

http://doc.pypy.org/en/latest/cpython_differences.html#subclasses-of-built-in-types

**Comment by bdcht** [comment]
Hi. Indeed, I will have a look a this issue tomorrow.  Thanks for reporting
it.

Le ven. 23 sept. 2016 10:25, Andre Pawlowski notifications@github.com a
écrit :

**Comment by bdcht** [comment]
I've revert generation to OrderedDict since anyway the 'history' of modified locations provided by the previous class was not used yet. Should fix this issue. Let me know.

**Comment by sqall01** [comment]
Hi,

thanks for the fix. I just tested it and it seems to work fine :+1:
