### ISSUE TITLE
x64 writing to 32bit register

### ISSUE THREAD

**Issue by sqall01** [bdcht/amoco#77]
Hi,

I have the following instruction:

`lea         ecx, [(rax+rdx)]`

Before execution the mapper has the following state for "rcx":

`rcx <- { | [0:64]->(0xfffffffffffff164) | }`

After execution it has:

`rcx <- { | [0:32]->(0x1d4d79476)[0:32] | [32:64]->(0xfffffffffffff164)[32:64] | }`

The upper part [32:64] is wrong. The intel manual states that when only the 32bit of the 64bit registers are written, the upper part is zeroed. [Here is a short summary for it](http://x86asm.net/articles/x86-64-tour-of-intel-manuals/).

I am just trying to fix it in the "def i_LEA(i,fmap)" function, but since I am not completely familiar with the architecture environment, I think my fix will be rather hacky.

Cheers,
sqall

**Comment by bdcht** [comment]
damned...these quirks drive me crazy.
i_LEA is the right place to fix it, but I need to check if this behavior is coherent with x86 writting to 16-bits regs first because the current implementation seems to handle this case already.
thanks for reporting this!
stay tuned

**Comment by bdcht** [comment]
fixed by commit f45bcd3.

tested with instructions 
'678d0c10'        lea         ecx, [(eax+edx)]                => modifies rcx with zeroextended ecx
'66678d0c10'    lea         cx, word ptr [(eax+edx)]    => modifies only lower 16-bits of rcx

thanks;
Axel

**Comment by bdcht** [comment]
was badly fixed for lea ecx, [(rax+rdx)] or lea rcx, [(eax+edx)].
should be ok now with v2.5.3, tested on these cases too...

**Comment by sqall01** [comment]
Thank you very much. Yeah, the x86 quirks are a headache. And especially that it behaves differently for 16bit registers and 32bit registers :/
