### ISSUE TITLE
Sparc formatter

### ISSUE THREAD

**Issue by LRGH** [bdcht/amoco#84]
This one also worked before.
```
from amoco.arch.sparc import cpu_v8
from amoco.arch.sparc.parsers import sparc_syntax
from amoco.ui import render
render.conf.UI.formatter = 'Null'

s = "ld [%g1], %g1" 
i = sparc_syntax.instr.parseString(s)[0]
assert str(i) == 'ld  [%g1], %g1'
```

**Comment by bdcht** [comment]
should be fixed now, only the mnemonic is ljust to length 8 so your assert should be adjusted as well. This mnemonic format parameter should probably be configurable but unfortunately its still hardcoded at the moment.
