### ISSUE TITLE
commit 25846af60fc9ba6787429d6f1093e8b1bf9f8492 broke at least lfence 

### ISSUE THREAD

**Issue by LRGH** [bdcht/amoco#90]
```
>>> from amoco.arch.x64 import cpu_x64 as cpu
>>> i = cpu.disassemble(b'\x0f\xae\xe8')
>>> print(i)
lfence      eax
```

The output should be `lfence`, which is the syntax understood by GNU as for example and is the output prior to this commit.

**Comment by bdcht** [comment]
Hi thanks, hopefully hotfixed by 8f04f58

**Comment by LRGH** [comment]
Yes, thank you.
I will continue working on the merge of my fork with your most recent version...
